import Head from 'next/head'
import { getRuntimeConfigRequired } from '@/environment/next.publicRuntimeConfig'
import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    console.log("sentryDsn", getRuntimeConfigRequired('sentryDsn'));
    console.log("sentryEnvironment", getRuntimeConfigRequired('sentryEnvironment'));
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>hello</p>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const response = await fetch("https://httpbin.org/get")
  const data = await response.json()

  return { props: data };   
}